### PR TITLE
Refactored several controls.

### PR DESCRIPTION
**Pull request by manthey**
Adjusted controls for rebinning.

Refactored animation controls.

If Instagram messages have been loaded, make them the default graph data set rather than temperature.

When we aren't using a database for a long time, disconnect from it.  Connection seems to only take 20 milliseconds, and this makes it easier for me to update databases in place, and for some resources to be freed.

Removed backbone from the package list, as we don't need to install it (it comes with Girder).

### CODE REVIEW

**Comment by manthey** [comment]
Resolves issues #97 and #95.

**Comment by jeffbaumes** [comment]
This looks very good - much easier to follow. Perhaps "Window size" instead of "Group" might be a better name for that control - with the tooltip saying "time interval" instead of "time period". Duration and Rate seem like a big step up in usability.

**Comment by manthey** [comment]
I'll change to "Window" and "time interval".  The animation is much easier
to explain with the new controls -- thanks for suggesting the changes.

Do you think I should add or remove any of options for various select boxes?

On Thu, May 21, 2015 at 11:01 AM, Jeffrey Baumes notifications@github.com
wrote:

> This looks very good - much easier to follow. Perhaps "Window size"
> instead of "Group" might be a better name for that control - with the
> tooltip saying "time interval" instead of "time period". Duration and Rate
> seem like a big step up in usability.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/XDATA-Year-3/geoapp/pull/99#issuecomment-104311239.

## 

David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by jeffbaumes** [comment]
Not sure the utility of 3 hour window - do you find it useful?

**Comment by manthey** [comment]
I thought I could see some effects better with it.  For instance, with one
of the protests, the activity lasted several hours, and I thought the
activity change viewed through the hour window wasn't as clear as the
activity change through a longer window (but a day was too long).

On Thu, May 21, 2015 at 12:03 PM, Jeffrey Baumes notifications@github.com
wrote:

> Not sure the utility of 3 hour window - do you find it useful?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/XDATA-Year-3/geoapp/pull/99#issuecomment-104332702.

## 

David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Pull request merged**
