### PR TITLE
Support real-time data

### PR DESCRIPTION
**Pull request by manthey**
Added an ingest endpoint.  Currently this only supports twitter data.

Added support for a new database type with a GET message endpoint.  This database is nearly compatible with the instagram endpoint, so the two endpoints can mostly share databases.

Left to do:
- [x] Handle missing latitude and longitudes
- [x] Requery (or have a websocket or webworker) for automatic refresh

### CODE REVIEW

**Comment by manthey** [comment]
For the moment, I will add a query flag that, by default, will not load points without latitude or longitude.  Eventually, I could see having a user interface option for this, and those points would either not be plotted on the map (but would show in the histogram and in the list), or would be placed at their location using a different color to indicate that they are not geo-located.  Suggestions welcome.

**Comment by jeffbaumes** [comment]
This sounds like a good plan. Are you planning to have a "cursor" for realtime data queries so multiple clients can be connected at once without interfering? Or will you use polling each client keeping track of the timestamp it currently has data for?

**Comment by manthey** [comment]
For the realtime database, I have an _id value which is a int64 sequence for the order the data is added. Each client polls, not by timestamp, but by this _id (ask for any data with an _id higher than the highest _id that existed from the last query).  This means that data can be added out of order (imagine that a feed drops, and we have to ingest old data, but it is new to the client).

I'm using polling, as I'm not sure how to keep a standing query in postgres.  The poll interval is adjustable.  If we want sub-second update rates for a high-volume feed, we probably will need a more complex mechanism.

**Comment by jeffbaumes** [comment]
Ok sounds like a decent plan.

**Pull request merged**
